### ISSUE TITLE
Bug in calculation the fraction

### ISSUE THREAD

**Issue by mam-mih-val** [HeavyIonAnalysis/QnTools#12]
@kreisl, developing the inteface for resolution and flow calculation I faced the problem.

Here's the bug:
Division of multidimensional data container of stats by _non-zero_ one-dimensional data container gives inf/nan in result container.
In the same time, making projection on one axis, gives adequate result. And projection on two axis gives inf/nan too.

Numerator and denuminator are both refference-weighted.

**Comment by kreisl** [comment]
Could you write a short example which reproduces this problem? It makes it easier to check and then I can add it to the unit tests to make sure this case is covered.

**Comment by mam-mih-val** [comment]
Here's the small root macro reproducing the problem.
https://github.com/mam-mih-val/qn_tools_test

**Comment by mam-mih-val** [comment]
Upd: Inf/nan is on Viktor's fork version. On current version of this repo result histo ("flow") is not filled at all.

**Comment by kreisl** [comment]
@mam-mih-val can you try with the branch [kreisl:projectiontest](https://github.com/kreisl/QnTools/tree/projectiontest). It only appears if we have empty bins in the merging. It should fix the issues you are seeing? Please take note to merge bins after dividing we need to set the numerator as observable, to know which weight to take? In your example https://github.com/mam-mih-val/qn_tools_test i think you need to edit the lines like so:
```
Qn::DataContainerStats flow = *container_un_qn;
for (auto & bin : flow) {
  bin.SetWeights(Qn::Stats::Weights::OBSERVABLE);
  bin.ResetBits(Qn::Stats::CORRELATEDERRORS);
}
flow = flow / resolution;
```
Somehow the correlated errors don't work that's why i disabled them. maybe we need to look in a separate test into this. Please let me know if it worked.

**Comment by mam-mih-val** [comment]
Yeah, the fix you offered works. But as I can remember, there was not such a bug in earlier versions, was it?

**Comment by kreisl** [comment]
Yes this could be at some point I cleaned up the logic. I think this is not perfect yet. We should discuss again all possible cases and make sure we have them all covered.
