### ISSUE TITLE
Proposal: remove static polymorphism of AddCutOnDetector

### ISSUE THREAD

**Issue by eugene274** [HeavyIonAnalysis/QnTools#20]
Hi again!

For the same reason as #19  I propose to change signature (or maybe overload) of AddCutOnDetector by 

void AddCutOnDetector(std::string name, std::vector<std::string> args, bool (double * args));

**Comment by kreisl** [comment]
This is a bigger one. I think this is not as easy to implement. As far as I see you will have to change the way the cuts work. Which might be a good idea. Right now they call a std::function(double,...), which expects as many parameters as variables go into the cut. Since this needs to be known at compile time there is no way around this template parameter. Maybe you can find another solution like passing the parameters as vector to the function and sort it out in the cut itself which is set by the user.
