### ISSUE TITLE
Problem with Bootstrap error in Qn::DataContainerStatCalculate

### ISSUE THREAD

**Issue by mam-mih-val** [HeavyIonAnalysis/QnTools#42]
Dear @kreisl,
I faced a problem with error calculation using bootstrapping in Qn::DataContainerStatCalculate. I read Qn::DataContainerStatCollect (correlations after correlation task) from file, then convert this containers to StatCalculate type and perform resolution calculation. And if I use bootstrap flag for error calculation, I get almost 50% errors on their relative value. At the same time if I switch to propagation error type, I get rather smaller errors. The correlations were filled using 50 samples.
So, can you please tell if I do something wrong, and if not check if there's a bug in error calculation with bootstrapping.

**Comment by mam-mih-val** [comment]
This short program demonstrates the problem appearance.
https://github.com/mam-mih-val/qn_tools_test

**Comment by kreisl** [comment]
Thanks for the info. I noticed something similar. With your example I pinned it down to the operation Qvector * scalar.
I will investigate.
Current Implementation:
The means of the bootstrap samples are multiplied by the same scalar. The error is calculated from the variance of the resulting distribution.
Problem:
push_back creates new entries instead of modifying existing entries. I will push a fix soon.
